name: tarot

services:
  backend:
    build:
      context: .
    ports:
      - "3535:3535"
    networks:
      - back-tier
    healthcheck:
      test: curl --fail http://localhost:4444/health
      interval: 30s
      timeout: 5s
      retries: 3
      start_period: 30s

volumes:
  pictures: {}
  logs: {}
  postgres_data: {}
  redis_data: {}

networks:
  back-tier: {}